select b.CL_ID,a.UNQ_ID_SRC_STM COD_EMP,b.DSC AS IDE_EMP,b.NM NOM_EMP
FROM BDWH_SOR..CL_SRC_STM_CODE (NOLOCK) A
INNER JOIN BDWH_SOR..CV (NOLOCK) B ON (A.CL_SCM_ID=B.CL_SCM_ID AND A.CL_SCM_SEQ_NO = B.CL_SCM_SEQ_NO)
WHERE A.CL_SCM_ID = 523
AND A.END_DT IS NULL AND B.END_DT IS NULL
AND a.UNQ_ID_SRC_STM IS NOT NULL
